### ISSUE TITLE
TODO: Basic things missing that make it just a PoC

### ISSUE THREAD

**Issue by dpc** [dpc/async-readline#4]
* [ ] restore normal mode on exit (on drop)
* [ ] ability to finish the
* [ ] detect Ctrl+C, Ctrl+D and pass to the user #1 
* [ ] arrow keys support
* [ ] Windows support #3 
* [ ] detect TTY fallback to non-interactive mode

Afterwards:

* [ ] history
* [ ] some form of autocompletion
